#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Mon Jul 06 22:32:29 EDT 2026
alwaysLogTamperWarnings=true
